site_name: My Docs
site_url: https://gaduby.github.io/learning-electronics/


theme:
  name: material
  features:
      - content.code.copy
      - content.code.annotate
  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
    icon: material/brightness-4
    name: Switch to light mode

plugins:
  - search

markdown_extensions:
- attr_list
- md_in_html
- admonition
- def_list

# Python Markdown Extensions
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.details
- pymdownx.blocks.tab
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
    clickable_checkbox: true
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.tilde
- pymdownx.betterem