site_name: Learning Electronics and Circuits
site_url: https://gaduby.github.io/learning-electronics/


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search
  - ezlinks

markdown_extensions:
- attr_list
- md_in_html
- admonition
- def_list

# Python Markdown Extensions
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.details
- pymdownx.blocks.tab
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
    clickable_checkbox: true
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.tilde
- pymdownx.betterem